from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATASET_DIR = PROJECT_ROOT / "dataset"

CURRENT_TRAIN_DIR = DATASET_DIR / "current"
REPLAY_DIR = DATASET_DIR / "replay"
VAL_DIR = DATASET_DIR / "val"

MODELS_DIR = PROJECT_ROOT / "models"
MODEL_PATH = MODELS_DIR / "image_preference_model.pt"
LATEST_MODEL_PATH = MODELS_DIR / "image_preference_model.latest.pt"

OUTPUTS_DIR = PROJECT_ROOT / "outputs"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

IMAGE_SIZE = 224
DEFAULT_BATCH_SIZE = 32
DEFAULT_EPOCHS = 30
DEFAULT_LEARNING_RATE = 5e-5

DEFAULT_DISTILL_WEIGHT = 0.5
DEFAULT_WEIGHT_DRIFT_WEIGHT = 1e-4
DEFAULT_DISTILL_TEMPERATURE = 2.0

# Replay settings
DEFAULT_REPLAY_FRACTION = 0.20
DEFAULT_REPLAY_MAX_PER_CLASS = 500
DEFAULT_REPLAY_SEED = 42

# Auto-validation settings
DEFAULT_AUTO_VAL_FRACTION = 0.20
DEFAULT_AUTO_VAL_MAX_PER_CLASS = 200
DEFAULT_AUTO_VAL_SEED = 123

# Early stopping settings
DEFAULT_EARLY_STOPPING_ENABLED = True
DEFAULT_EARLY_STOPPING_PATIENCE = 3
DEFAULT_MIN_DELTA = 0.0001
DEFAULT_EARLY_STOPPING_METRIC = "balanced_accuracy"

# Auto checkpoint testing / best epoch selection
DEFAULT_AUTO_TEST_ENABLED = True
DEFAULT_SELECTION_METRIC = "balanced_accuracy"
DEFAULT_DETAILED_TEST = False

NUM_WORKERS = 0

CLASS_NAMES = ["0", "1"]
